### ISSUE TITLE
Erro no import do método getBooleanFromString

### ISSUE THREAD

**Issue by pedrominare** [FeTads/otxserver#4]
Identifiquei que os mods/ não estão importando o método getBooleanFromString das libs, mais especificamente da lib/011-string.lua. Testei criar o método em outra lib, como 050-function.lua mas mesmo assim não foi possível importar, o método não é reconhecido no script.xml do mod.

**Comment by FeTads** [comment]
os mods não reconhecem funções da lib mesmo, encessário adicionar dentro do proprio mod a função.
